CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(250) NOT NULL,
  email VARCHAR(250) UNIQUE NOT NULL,
  senha VARCHAR(250) NOT NULL,
  funcao VARCHAR(250) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS processos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descricao  VARCHAR(250)
);

CREATE TABLE IF NOT EXISTS processos_usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE CASCADE,
    processo_id INT NOT NULL REFERENCES processos(id) ON UPDATE CASCADE ON DELETE CASCADE
);
