DROP TABLE IF EXISTS usuarios;
  
CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  senha VARCHAR(250) NOT NULL,
  funcao VARCHAR(250) DEFAULT NULL
);